#ifndef CDNUEVOEVENTO_H
#define CDNUEVOEVENTO_H

//(*Headers(CDNuevoEvento)
#include <wx/dialog.h>
#include <wx/textctrl.h>
//*)

#include "Main.h"

namespace InterfazSancho	{
/**
  * This very basic dialog box is used to name a new event. ShowModal and the actions to take on OK are automatic.
  * Some parts of this class' skeleton are generated by Codeblocks.
  * \sa Main
  */
class CDNuevoEvento: public wxDialog
{
	public:

		CDNuevoEvento(Main* parent);	//!< Constructor. The parent must be a Main object.
		virtual ~CDNuevoEvento()	{}	//!< Virtual destructor.

		//(*Declarations(CDNuevoEvento)
		wxTextCtrl *nombre;	//!< Name of the event.
		//*)

	protected:

		//(*Identifiers(CDNuevoEvento)
		const static long ID_NOMBRE;
		const static long ID_OK;
		const static long ID_CANCEL;
		//*)

	private:

		//(*Handlers(CDNuevoEvento)
		//*)

		Main *panel;	//!< Parent.

		DECLARE_EVENT_TABLE()
		void OnOK(wxEvent &);
		void OnCancel(wxEvent &);
};
}	//End of namespace
#endif
