#ifndef CDTRANSICION_H
#define CDTRANSICION_H

//(*Headers(CDTransicion)
#include <wx/dialog.h>
#include <wx/combobox.h>
#include <wx/textctrl.h>
//*)

#include "Transicion.h"
#include "TabSentenciasSimple.h"

namespace InterfazSancho	{
/**
  * This class contains the definition of a dialog box used to configurate a transition between states. The constructor calls automatically ShowModal and updates the
  * Transicion object automatically if the OK button is pressed.
  * Part of this class' skeleton was generated by Codeblocks.
  * \sa Transicion
  */
class CDTransicion: public wxDialog
{
	public:

		CDTransicion(wxWindow* parent,const TransicionPtr &t);	//!< Constructor.
		virtual ~CDTransicion()	{}	//!< Virtual destructor.

		//(*Declarations(CDTransicion)
		wxComboBox *entrante;	//!< Combo box to select the destination state.
		wxComboBox *evento;	//!< Combo box to optionally choose the event this transition is waiting for.
		wxTextCtrl *condicion;	//!< Text control to optionally enter the condition this transition is waiting to occur.
		TabSentenciasSimple *tabSentencias;	//!< Instructions panel.
		//*)

	protected:

		//(*Identifiers(CDTransicion)
		const static long ID_ENTRANTE;
		const static long ID_EVENTO;
		const static long ID_CONDICION;
		const static long ID_OK;
		const static long ID_CANCEL;
		//*)

	private:

		//(*Handlers(CDTransicion)
		//*)

		TransicionPtr trans;	//!< Transition to which this dialog box is linked. Will be automatically updated on OK.

		DECLARE_EVENT_TABLE()
		void OnOK(wxEvent &);
		void OnCancel(wxEvent &);
};
}	//End of namespace
#endif
