#ifndef VENTANAP_H
#define VENTANAP_H

//(*Headers(VentanaD)
#include <wx/dialog.h>
#include <wx/spinctrl.h>
//*)

#include "EstadoParalelo.h"

#include <vector>

namespace InterfazSancho	{
class PanelGraf;
/**
  * Whenever the user tries to create a parallel state, this dialog box is called to determine the amount of parallel children.
  * Some parts of this class' skeleton have been generated by Codeblocks.
  * \sa EstadoParalelo, PanelGraf
  */
class VentanaP: public wxDialog
{
	public:
		VentanaP(PanelGraf *p,int px,int py,const std::vector<DibujablePtr> &ep=std::vector<DibujablePtr>(0));	//!< Constructor. The parent must be a PanelGraf object.
		virtual ~VentanaP()	{}	//!< Destructor.

		//(*Declarations(VentanaD)
		wxSpinCtrl *s;	//!< Spin control to select the amount of children (2-20).
		//*)

	protected:

		//(*Identifiers(VentanaD)
		static const long ID_ADJ;
		static const long ID_OK;
		static const long ID_CANCEL;
		//*)

	private:

		//(*Handlers(VentanaD)
		//*)

		std::vector<DibujablePtr> jer;	//!< Hierarchy into which the state is to be created. If it's null, the state will be created at top-level.
		int vx,vy;	//!< Position.
		PanelGraf *padre;	//!< Parent panel.

		DECLARE_EVENT_TABLE()

		void OnOK(wxEvent &);
		void OnCancel(wxEvent &);
};
}	//End of namespace
#endif
